### ISSUE TITLE
Diagrama de componentes

### ISSUE THREAD

**Issue by edgarmauricio123** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equipo-1-1#1]
[DIAGRAMA DE COMPONENTES REPORTE ORIGINAL.pdf](https://github.com/user-attachments/files/18043676/DIAGRAMA.DE.COMPONENTES.REPORTE.ORIGINAL.pdf)

**Comment by Ariadnamonserrat10** [comment]
28 de 30 ya que esta bien expresado, solamente falto el indice y unas pocas imagenes

**Comment by josealfredo79** [comment]
revisado...
